export const initialPosition = [
  {
    position: "a2",
    name: "blackpawn_1",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "b2",
    name: "blackpawn_2",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "c2",
    name: "blackpawn_3",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "d2",
    name: "blackpawn_4",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "e2",
    name: "blackpawn_5",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "f2",
    name: "blackpawn_6",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "g2",
    name: "blackpawn_7",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "h2",
    name: "blackpawn_8",
    color: "black",
    image: "./images/bp.png",
  },
  {
    position: "a1",
    name: "blackrook_1",
    color: "black",
    image: "./images/br.png",
  },
  {
    position: "h1",
    name: "blackrook_2",
    color: "black",
    image: "./images/br.png",
  },
  {
    position: "b1",
    name: "blackknight_2",
    color: "black",
    image: "./images/bn.png",
  },
  {
    position: "g1",
    name: "blackknight_1",
    color: "black",
    image: "./images/bn.png",
  },
  {
    position: "c1",
    name: "blackbishop_1",
    color: "black",
    image: "./images/bb.png",
  },
  {
    position: "f1",
    name: "blackbishop_2",
    color: "black",
    image: "./images/bb.png",
  },
  {
    position: "d1",
    name: "blackqueen",
    color: "black",
    image: "./images/bq.png",
  },
  {
    position: "e1",
    name: "blackking",
    color: "black",
    image: "./images/bk.png",
  },
  {
    position: "a8",
    name: "whiterook_2",
    color: "white",
    image: "/images/wr.png",
  },
  {
    position: "b8",
    name: "whiteknight_2",
    color: "white",
    image: "/images/wn.png",
  },
  {
    position: "c8",
    name: "whitebishop_2",
    color: "white",
    image: "/images/wb.png",
  },
  {
    position: "d8",
    name: "whitequeen",
    color: "white",
    image: "/images/wq.png",
  },
  {
    position: "e8",
    name: "whiteking",
    color: "white",
    image: "/images/wk.png",
  },
  {
    position: "f8",
    name: "whitebishop_1",
    color: "white",
    image: "/images/wb.png",
  },
  {
    position: "g8",
    name: "whiteknight_1",
    color: "white",
    image: "/images/wn.png",
  },
  {
    position: "h8",
    name: "whiterook_1",
    color: "white",
    image: "/images/wr.png",
  },
  {
    position: "a7",
    name: "whitepawn_8",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "b7",
    name: "whitepawn_1",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "c7",
    name: "whitepawn_2",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "d7",
    name: "whitepawn_3",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "e7",
    name: "whitepawn_4",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "f7",
    name: "whitepawn_5",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "g7",
    name: "whitepawn_6",
    color: "white",
    image: "/images/wp.png",
  },
  {
    position: "h7",
    name: "whitepawn_7",
    color: "white",
    image: "/images/wp.png",
  },
];
